### ISSUE TITLE
Has this solution been tested with bag data?

### ISSUE THREAD

**Issue by JACKLiuDay** [LihanChen2004/small_gicp_relocalization#1]
Hello, thank you for sharing the open-source work. I would like to ask if this project has been tested in real-world map and point cloud localization?

**Comment by LihanChen2004** [comment]
I recorded a rosbag using Livox mid360 in my campus hallway.

Using Pointlio to create a prior pointcloud map.

I played the rosbag again and wait a few senconds to move the LiDAR a certain distance (about 0.5m), then start the small_gicp_relocalization package. small_gicp was able to output correct transformations from `map` to `odom`, and while there were some matching failures in the narrow stairway area, point cloud registration worked correctly in most other scenarios.

This package is still a small prototype, and I have not yet tested it on publicly available academic datasets.

![image](https://github.com/user-attachments/assets/b726bd62-4373-4881-b451-5d353f30069d)

**Comment by JACKLiuDay** [comment]
> I recorded a rosbag using Livox mid360 in my campus hallway.
> 
> Using Pointlio to create a prior pointcloud map.
> 
> I played the rosbag again and wait a few senconds to move the LiDAR a certain distance (about 0.5m), then start the small_gicp_relocalization package. small_gicp was able to output correct transformations from `map` to `odom`, and while there were some matching failures in the narrow stairway area, point cloud registration worked correctly in most other scenarios.
> 
> This package is still a small prototype, and I have not yet tested it on publicly available academic datasets.
> 
> ![image](https://private-user-images.githubusercontent.com/74599182/398327980-b726bd62-4373-4881-b451-5d353f30069d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjMwNjgsIm5iZiI6MTczNTAyMjc2OCwicGF0aCI6Ii83NDU5OTE4Mi8zOTgzMjc5ODAtYjcyNmJkNjItNDM3My00ODgxLWI0NTEtNWQzNTNmMzAwNjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA2NDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZTU3ZTQ1ZWQyYzE2OWQ2MzQwNjdiNWU0NjFhZmY1ZGQyMGE4OWUzOGQ0MmE1YWI5ZmNhN2ViYzA0NDc2MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Om9fJXqnpa4hUjGAnwMn45h0lEWX-dahTpoI4uQgu6E)

Thank you for your reply. I plan to try this work with the ROS Noetic version, and I will reach out to you if I encounter any issues.
